<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
    <title>JSP Tags Example</title>
</head>
<body>

    <h2>JSP Tag Demonstration</h2>

    <%-- Scriptlet Tag: <% ... %> --%>
    <% 
        // This is a scriptlet. It's used to embed Java code within the HTML.
        String message = "This message was generated by a scriptlet.";
        int number = 10;
    %>

    <%-- Expression Tag: <%= ... %> --%>
    <p>Using an expression tag to display a variable: **<%= message %>**</p>
    <p>The result of a calculation: **<%= number * 5 %>**</p>

    <%-- Declaration Tag: <%! ... %> --%>
    <%! 
        // This is a declaration. It's used to declare methods or variables 
        // that are accessible to the entire JSP page.
        public String getGreeting() {
            return "Hello from a declaration tag!";
        }
    %>

    <p>Using a declaration tag to call a method: **<%= getGreeting() %>**</p>

</body>
</html>